name: diffdev
root: /home/quinten/Documents/Software_Development/diffdev

on_project_start: echo -ne "\033]0;diffdev\007"

windows:
  - editor:
      layout: main-vertical
      panes:
        - nv .
  - terminal:
      layout: even-horizontal
      panes:
        - clear
