name: Test Release Process

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Test version number (e.g. 0.1.3)'
        required: true
        type: string

# Add "test-" prefix to all job names to distinguish from real release
jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e '.[test]'
    - name: Run tests
      run: |
        python -m pytest

  test-deploy:
    runs-on: ubuntu-latest
    needs: [test-build]
    # Note: Remove the environment and permissions since we won't actually publish

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test version update
      run: |
        # Create temporary files to avoid modifying real ones
        cp src/diffdev/__init__.py src/diffdev/__init__.py.test
        cp pyproject.toml pyproject.toml.test

        # Test version updates
        VERSION=${{ inputs.version }}
        sed "s/__version__ = .*/__version__ = \"$VERSION\"/" src/diffdev/__init__.py > src/diffdev/__init__.py.test
        sed "s/version = .*/version = \"$VERSION\",/" pyproject.toml > pyproject.toml.test

        # Show diffs
        echo "Changes that would be made to __init__.py:"
        diff src/diffdev/__init__.py src/diffdev/__init__.py.test || true
        echo -e "\nChanges that would be made to pyproject.toml:"
        diff pyproject.toml pyproject.toml.test || true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: '**/pyproject.toml'

    - name: Install build
      run: |
        python -m pip install build

    - name: Test build package
      run: |
        # Build in a temp directory
        mkdir -p dist_test
        python -m build --outdir dist_test

        # Show what would be built
        echo "Files that would be published:"
        ls -l dist_test
